Add NL formatting rules
battre/autocomplete-attribute-explainer pull request #71
Opened 2024-10-24 20:06 UTC by Pitchiu

This PR adds formatting rules for the Netherlands.

2024-10-24 20:06 UTC, Pitchiu commented
@norgevz could you take a look?

2024-10-25 11:17 UTC, skyman503 approved these changes
Lgtm thanks!

2024-10-25 11:28 UTC, norgevz commented on model/countries/NL/NL-formatting-rules.yaml
> +  - skip: admin-area1 # not commonly used
Could you add to the PR description the main sources that you used to build these expressions? I'm also interested in the following questions:

1. Is okay to always use `-` as the separator building and unit?
2. Is state (admin-area1) really not used in the Netherlands?

2024-10-25 13:47 UTC, norgevz requested changes
LGTM

Thanks!

2024-10-25 13:47 UTC, norgevz approved these changes

2024-10-25 13:52 UTC, merged